model_class: 'DeepLab'
experiment_name: 'DeepLabV3Plus_baseline'
dataset_class: 'PascalVOC2012_dataset'
save_freq: 1
is_classification: False
n_classes: 21
use_dynamic : False 
max_epoch: 50 
batch_size: 16
batch_average: True
optimizer : "SGD"
optimizer_args : (0.007, 0.9, 0, 5e-4) 
scheduler : "StepLR"
scheduler_args : (15, 0.1)
num_workers: 4
device : "cuda"