model_class: 'MobileNetV2'
dataset_class: 'TinyImageNet_dataset'
save_freq: 5
batch_size: 320
num_workers: 2
device: 'cuda'
max_epoch: 300
experiment_name: 'MobileNetV2_dy'
use_dynamic: True
scheduler: 'CosineAnnealingLR'
scheduler_args: (300, 0)
optimizer: 'SGD'
optimizer_args: (0.05, 0.9, 0, 4e-5) #(lr, momentum, dampening, weight decay)